import Link from "next/link";

type SuccessPageProps = {
  searchParams: Promise<{
    request?: string | string[];
    quote?: string | string[];
    status?: string | string[];
  }>;
};

export default async function CustomPrintingSuccessPage({ searchParams }: SuccessPageProps) {
  const params = await searchParams;
  const requestId = Array.isArray(params.request) ? params.request[0] : params.request;
  const quoteNumber = Array.isArray(params.quote) ? params.quote[0] : params.quote;
  const status = Array.isArray(params.status) ? params.status[0] : params.status;
  const statusFlow = ["Quote Requested", "Quote Sent", "Approved", "In Production", "Completed"];

  return (
    <main className="min-h-screen bg-[#050505] px-6 pb-20 pt-32 text-[#f7f0e6] md:px-10">
      <div className="mx-auto max-w-5xl rounded-[2.2rem] border border-[#f3e5cf]/10 bg-gradient-to-br from-[#f6ead7]/[0.08] via-white/[0.03] to-transparent p-8 shadow-[0_30px_120px_rgba(0,0,0,0.45)] md:p-10">
        <p className="text-[11px] uppercase tracking-[0.32em] text-[#d2bea0]">Custom Printing</p>
        <h1 className="mt-5 font-serif text-4xl md:text-6xl text-[#fff7ed]">Thank you.</h1>
        <p className="mt-5 max-w-2xl text-base leading-8 text-[#d7c9b5]">
          Your inquiry has been received.
        </p>

        <div className="mt-10 grid gap-4 md:grid-cols-3">
          <div className="rounded-[1.5rem] border border-[#f3e5cf]/10 bg-black/55 p-5">
            <p className="text-[11px] uppercase tracking-[0.28em] text-[#d2bea0]">Reference Number</p>
            <p className="mt-3 text-xl font-medium text-[#fff7ed]">{quoteNumber ?? "Generated by production team"}</p>
          </div>
          <div className="rounded-[1.5rem] border border-[#f3e5cf]/10 bg-black/55 p-5">
            <p className="text-[11px] uppercase tracking-[0.28em] text-[#d2bea0]">Status</p>
            <p className="mt-3 text-xl font-medium text-[#fff7ed]">{status ?? "Quote Requested"}</p>
          </div>
          <div className="rounded-[1.5rem] border border-[#f3e5cf]/10 bg-black/55 p-5">
            <p className="text-[11px] uppercase tracking-[0.28em] text-[#d2bea0]">Reference</p>
            <p className="mt-3 break-all text-sm text-[#efe3d3]">{requestId ?? "Sent to support@leochi.co"}</p>
          </div>
        </div>

        <div className="mt-10 rounded-[1.7rem] border border-[#f3e5cf]/10 bg-black/40 p-6">
          <p className="text-[11px] uppercase tracking-[0.28em] text-[#d2bea0]">Status Flow</p>
          <div className="mt-5 grid gap-4 md:grid-cols-5">
            {statusFlow.map((item, index) => {
              const active = item === (status ?? "Quote Requested");
              const completed = statusFlow.indexOf(status ?? "Quote Requested") >= index;

              return (
                <div key={item} className={`rounded-[1.2rem] border px-4 py-4 transition ${active ? "border-[#f3e5cf]/35 bg-[#f3e5cf]/[0.08]" : completed ? "border-[#f3e5cf]/20 bg-[#f3e5cf]/[0.04]" : "border-white/10 bg-black/25"}`}>
                  <p className="text-[10px] uppercase tracking-[0.26em] text-[#d2bea0]">0{index + 1}</p>
                  <p className="mt-2 text-sm text-[#fff7ed]">{item}</p>
                </div>
              );
            })}
          </div>
        </div>

        <div className="mt-10 flex flex-col gap-4 sm:flex-row">
          <Link
            href="/custom-printing"
            className="inline-flex items-center justify-center rounded-full bg-[#f3e5cf] px-7 py-4 text-xs font-semibold uppercase tracking-[0.24em] text-black transition hover:bg-[#fff4e4]"
          >
            Start Another Request
          </Link>
          <Link
            href="/shop"
            className="inline-flex items-center justify-center rounded-full border border-[#f3e5cf]/20 px-7 py-4 text-xs font-semibold uppercase tracking-[0.24em] text-[#fff7ed] transition hover:border-[#f3e5cf]/50 hover:bg-[#f3e5cf]/[0.05]"
          >
            Back to Shop
          </Link>
        </div>
      </div>
    </main>
  );
}