create table if not exists public.admin_push_tokens (
  id bigint generated by default as identity primary key,
  token text not null unique,
  platform text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now()
);

create or replace function public.set_admin_push_tokens_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_admin_push_tokens_updated_at on public.admin_push_tokens;

create trigger trg_admin_push_tokens_updated_at
before update on public.admin_push_tokens
for each row
execute function public.set_admin_push_tokens_updated_at();

create index if not exists idx_admin_push_tokens_active
on public.admin_push_tokens (is_active);
