create table if not exists public.admin_push_tokens (
  id bigint generated by default as identity primary key,
  token text not null unique,
  created_at timestamptz not null default now()
);

alter table if exists public.admin_push_tokens
  add column if not exists created_at timestamptz not null default now();

create unique index if not exists idx_admin_push_tokens_token
on public.admin_push_tokens (token);

create table if not exists public.notification_logs (
  id bigint generated by default as identity primary key,
  title text not null,
  body text not null,
  order_id text,
  created_at timestamptz not null default now()
);

create index if not exists idx_notification_logs_created_at
on public.notification_logs (created_at desc);

create index if not exists idx_notification_logs_order_id
on public.notification_logs (order_id);
