import { CartProvider } from "./context/cartcontext";

import Navbar from "./components/navbar";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-[#fbf7f1]">
  <CartProvider>

    <Navbar />

    {children}

    <footer className="border-t mt-32 py-10 text-center text-gray-500">
      © 2026 LEOCHI. All rights reserved.
    </footer>

  </CartProvider>
</body>
    </html>
  );
}
