begin;

create table if not exists public.admin_push_tokens (
  id bigint generated by default as identity primary key,
  token text not null unique,
  created_at timestamptz not null default now()
);

alter table if exists public.admin_push_tokens
  add column if not exists platform text,
  add column if not exists is_active boolean not null default true,
  add column if not exists last_seen_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

create unique index if not exists idx_admin_push_tokens_token
on public.admin_push_tokens (token);

create index if not exists idx_admin_push_tokens_active
on public.admin_push_tokens (is_active);

create or replace function public.set_admin_push_tokens_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_admin_push_tokens_updated_at on public.admin_push_tokens;

create trigger trg_admin_push_tokens_updated_at
before update on public.admin_push_tokens
for each row
execute function public.set_admin_push_tokens_updated_at();

commit;
