begin;

create table if not exists public.notification_logs (
  id bigint generated by default as identity primary key,
  title text not null,
  body text not null,
  order_id text,
  created_at timestamptz not null default now()
);

create index if not exists idx_notification_logs_created_at
on public.notification_logs (created_at desc);

create index if not exists idx_notification_logs_order_id
on public.notification_logs (order_id);

commit;
